// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: pkg/wal/walpb/record.proto

package walpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int64                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Crc           uint32                 `protobuf:"varint,2,opt,name=crc,proto3" json:"crc,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_pkg_wal_walpb_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_wal_walpb_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_pkg_wal_walpb_record_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Record) GetCrc() uint32 {
	if x != nil {
		return x.Crc
	}
	return 0
}

func (x *Record) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Snapshot is a lightweight marker written to the WAL to record
// that a snapshot was taken at the given term and index.
type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_pkg_wal_walpb_record_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_wal_walpb_record_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_pkg_wal_walpb_record_proto_rawDescGZIP(), []int{1}
}

func (x *Snapshot) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Snapshot) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

var File_pkg_wal_walpb_record_proto protoreflect.FileDescriptor

const file_pkg_wal_walpb_record_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/wal/walpb/record.proto\x12\x05walpb\"B\n" +
	"\x06Record\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x03R\x04type\x12\x10\n" +
	"\x03crc\x18\x02 \x01(\rR\x03crc\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"4\n" +
	"\bSnapshot\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04termBDZBgithub.com/harshithgowda/distributed-key-value-store/pkg/wal/walpbb\x06proto3"

var (
	file_pkg_wal_walpb_record_proto_rawDescOnce sync.Once
	file_pkg_wal_walpb_record_proto_rawDescData []byte
)

func file_pkg_wal_walpb_record_proto_rawDescGZIP() []byte {
	file_pkg_wal_walpb_record_proto_rawDescOnce.Do(func() {
		file_pkg_wal_walpb_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_wal_walpb_record_proto_rawDesc), len(file_pkg_wal_walpb_record_proto_rawDesc)))
	})
	return file_pkg_wal_walpb_record_proto_rawDescData
}

var file_pkg_wal_walpb_record_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_wal_walpb_record_proto_goTypes = []any{
	(*Record)(nil),   // 0: walpb.Record
	(*Snapshot)(nil), // 1: walpb.Snapshot
}
var file_pkg_wal_walpb_record_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_wal_walpb_record_proto_init() }
func file_pkg_wal_walpb_record_proto_init() {
	if File_pkg_wal_walpb_record_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_wal_walpb_record_proto_rawDesc), len(file_pkg_wal_walpb_record_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_wal_walpb_record_proto_goTypes,
		DependencyIndexes: file_pkg_wal_walpb_record_proto_depIdxs,
		MessageInfos:      file_pkg_wal_walpb_record_proto_msgTypes,
	}.Build()
	File_pkg_wal_walpb_record_proto = out.File
	file_pkg_wal_walpb_record_proto_goTypes = nil
	file_pkg_wal_walpb_record_proto_depIdxs = nil
}
